server:
  port: 8081

spring:
  profiles:
    active:
      - dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath:/mapper/*.xml

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  file:
    name: backend-log.log