server:
  port: 11451

spring:
  thymeleaf:
    check-template-location: false
  profiles:
    active:
      - dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    admin:
      enabled: true
    name: trace-job
  boot:
    admin:
      client:
        url: http://127.0.0.1:41919/
        instance:
          service-host-type: ip

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      show-details: always

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath:/mapper/*.xml

logging:
  config: classpath:logback-spring.xml

resources:
  avatar: http://localhost:11451/avatar/
  goods: http://localhost:11451/goods/
